const HTTP_STATUS_CODES = [
    { code: 200, name: 'OK', desc: 'Request succeeded. Standard success for GET, PUT, PATCH.' },
    { code: 201, name: 'Created', desc: 'Resource created — typical POST response with Location header.' },
    { code: 204, name: 'No Content', desc: 'Success with empty body — common for DELETE.' },
    { code: 301, name: 'Moved Permanently', desc: 'URL permanently changed — update bookmarks and SEO redirects.' },
    { code: 302, name: 'Found', desc: 'Temporary redirect — client may keep using original URL.' },
    { code: 304, name: 'Not Modified', desc: 'Cached version still valid — saves bandwidth with ETag/If-None-Match.' },
    { code: 400, name: 'Bad Request', desc: 'Malformed syntax or invalid parameters — fix the client payload.' },
    { code: 401, name: 'Unauthorized', desc: 'Authentication missing or invalid — send valid credentials or token.' },
    { code: 403, name: 'Forbidden', desc: 'Authenticated but not allowed — user lacks permission for this resource.' },
    { code: 404, name: 'Not Found', desc: 'Resource or route does not exist — check URL and API version.' },
    { code: 405, name: 'Method Not Allowed', desc: 'HTTP verb not supported on this endpoint — e.g. POST on GET-only route.' },
    { code: 408, name: 'Request Timeout', desc: 'Client took too long to send the request.' },
    { code: 409, name: 'Conflict', desc: 'State conflict — duplicate email, version mismatch, concurrent edit.' },
    { code: 413, name: 'Payload Too Large', desc: 'Request body exceeds server limit — chunk uploads or reduce size.' },
    { code: 415, name: 'Unsupported Media Type', desc: 'Wrong Content-Type — send application/json if API expects JSON.' },
    { code: 422, name: 'Unprocessable Entity', desc: 'JSON parsed but validation failed — field-level errors in body.' },
    { code: 429, name: 'Too Many Requests', desc: 'Rate limit hit — backoff and read Retry-After header.' },
    { code: 500, name: 'Internal Server Error', desc: 'Unhandled exception on server — check logs, not client fault.' },
    { code: 502, name: 'Bad Gateway', desc: 'Upstream server returned invalid response — proxy/load balancer issue.' },
    { code: 503, name: 'Service Unavailable', desc: 'Server overloaded or in maintenance — retry with exponential backoff.' },
    { code: 504, name: 'Gateway Timeout', desc: 'Upstream did not respond in time — scale or fix downstream service.' },
];

const TOOL_EXAMPLES = {
    json: '{"site":"binodsuman.com","tools":["json","markdown","jwt"],"stats":{"videos":258}}',
    sql: 'SELECT u.id, u.name, COUNT(o.id) AS orders FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE u.active = 1 GROUP BY u.id ORDER BY orders DESC LIMIT 10;',
    xml: '<?xml version="1.0"?><user id="1"><name>Binod Suman</name><role>architect</role></user>',
    yaml: 'apiVersion: v1\nkind: Pod\nmetadata:\n  name: demo\nspec:\n  containers:\n  - name: app\n    image: nginx:alpine',
    markdown: '# Binod Suman Dev Tools\n\nFree **JSON**, **JWT**, and **Markdown** tools at [binodsuman.com/tools](https://binodsuman.com/tools/).\n\n- Browser-only\n- No upload\n\n```js\nconsole.log("hello");\n```',
    csv: 'name,role,country\nBinod Suman,Architect,India\nJane Doe,Engineer,USA',
    jsonArr: '[{"name":"Binod","role":"Architect"},{"name":"Jane","role":"Engineer"}]',
    jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzk5OSIsIm5hbWUiOiJCaW5vZCBTdW1hbiIsInJvbGVzIjpbImRldmVsb3BlciJdLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MTg1MDAwMDAwMH0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    base64: 'Binod Suman — dev tools on binodsuman.com',
    url: 'https://binodsuman.com/tools/?q=system design',
    unix: '1735689600',
    hash: 'binodsuman.com',
    curl: "curl -X POST 'https://api.example.com/users' -H 'Content-Type: application/json' -H 'Authorization: Bearer TOKEN' -d '{\"name\":\"Binod\"}'",
    apiUrl: 'https://jsonplaceholder.typicode.com/posts/1',
    k8sName: 'my-app', k8sImage: 'nginx:1.25', k8sReplicas: '2', k8sPort: '80',
    tokens: 'You are a senior architect. Explain URL shortener design for 10K writes/sec in under 300 words.',
    regexPattern: '\\b(JSON|JWT|API|SQL)\\b',
    regexText: 'Use JSON and JWT in your API. SQL stores the data.',
    cron: '0 9 * * 1-5',
    diffA: 'timeout: 30\nretries: 3',
    diffB: 'timeout: 60\nretries: 3\nregion: ap-south-1',
};
